### PR TITLE
Initial implementation of GridFS adapter

### PR DESCRIPTION
**Pull request by rodrigok**

### CODE REVIEW

**Comment by jalik** [comment]
You should add your credit to the package (email, etc) you did the job ;-)
I think you won the privilege to be the maintainer of this package, as you made it !
It will be easier and quicker for future changes.
Thank you @rodrigok !

**Comment by jalik** [comment]
Tell me when it's ok and I will merge !

**Comment by rodrigok** [comment]
Thanks :)

I did the change directly with my new repo permissions :smile_cat:

**Comment by jalik** [comment]
Welcome to OpenSourcing lol, I am sure your work will be useful for a lot of people ! I am already thinking about testing and implementing in the future ;-)

**Comment by rodrigok** [comment]
Thanks @jalik, I'm experiencing this with Rocket.Chat, it's awesome ;)

I've been thinking about tests too, but I don't have experience with tests at all :disappointed:

**Pull request merged**
